### ISSUE TITLE
How to use this layer in my model?

### ISSUE THREAD

**Issue by lemon0705-l** [wuhuikai/DeepGuidedFilter#11]
from guided_filter_pytorch.guided_filter import FastGuidedFilter

hr_y = FastGuidedFilter(r, eps)(lr_x, lr_y, hr_x)
r, eps，lr_x,lr_y,hr_xr,What are these parameters referring to?

from guided_filter_pytorch.guided_filter import GuidedFilter

hr_y = GuidedFilter(r, eps)(hr_x, init_hr_y)

**Comment by wuhuikai** [comment]
`r` & `eps` is hyper-params of GuidedFilter, where `r` is the radius of the filter and `eps` is a regulation term.
`lr_x` & `hr_x` is the low/high-resolution input image, `lr_y` is the low-resolution output.
