### ISSUE TITLE
why the layer cause unpleasant image blemishes

### ISSUE THREAD

**Issue by sangenan** [wuhuikai/DeepGuidedFilter#12]
could someone help me to deal with it？
![DSC00526_enhancer](https://user-images.githubusercontent.com/8358472/68096351-12576d80-feeb-11e9-94ed-75bea6d9fc44.JPG)

**Comment by wuhuikai** [comment]
Can you try to increase `eps` in the layer?

**Comment by sangenan** [comment]
thanks a lot, tune the right hyper-params can solve it
