### ISSUE TITLE
Why is Guided Filter not differentiable?

### ISSUE THREAD

**Issue by ericlearning** [wuhuikai/DeepGuidedFilter#15]
Hello!

I am having a hard time understanding the understanding a claim in the paper that the original guided filter is not differentiable.

Original guided filter does not have any learnable parameters in it, but aren't they still able flow the gradients backward as their operations (mean filter, linear operation) are differentiable?

Thanks.

**Comment by wuhuikai** [comment]
It is, but there's no backward procedure in the original paper.
