### ISSUE TITLE
About training auto-ps task on Fivek dataset

### ISSUE THREAD

**Issue by YinengXiong** [wuhuikai/DeepGuidedFilter#16]
Hello, I'm a beginer and I have some questions:

have you tried to train auto-ps task on fivek dataset at original image size?

the implementation in paper is resize to 512s and random resized from 512 to 1672 without data augmentation(e.g. random crop & random rotate) and you set fine-size = -1 in your default setting.

If i wanna train auto-ps task on the original image size, is it better to apply data augmentation(random crop, random flip & rotate) strategy?

thank you very much

**Comment by wuhuikai** [comment]
I didn't try this. But I think `rand crop` is necessary.
