### ISSUE TITLE
DGF code in segmentation

### ISSUE THREAD

**Issue by hedes1992** [wuhuikai/DeepGuidedFilter#2]
Thanks for your excellent work
When I view and run the code of "./ComputerVision/Deeplab-Resnet/predict_dgf.py" with the released pth file, I observed that the guided filter layer just work as the following:
![image](https://user-images.githubusercontent.com/14728901/37717110-f08005fe-2d5a-11e8-8827-145160abba09.png)
where the breakpoint is in ./ComputerVision/Deeplab-Resnet/deeplab_resnet.py
It seems that firstly using low-resolution image "x" to get low-resolution "output" and using original high-resolution image "im" to get guided_map "g", then upsample "output" to get coarse high-resolution "output", finally using guided_layer to get fine high-resolution "output".
In fact, in the guided_layer, it just calculate the A and b using guided_map "g" and coarse high-resolution "output", like the following:
![image](https://user-images.githubusercontent.com/14728901/37717552-bc0c1406-2d5b-11e8-989d-4310e9170dd4.png)
where the breakpoint is in ./GuidedFilteringLayer/GuidedFIlter_PyTorch/guided_filter_pytorch/guided_filter.py

So I cannot know whether there use the end-to-end guided layer in paper's Figure 2 like the following:
![image](https://user-images.githubusercontent.com/14728901/37717723-134703ac-2d5c-11e8-89bd-c4470d41c0f8.png)
I guess it's just the DGFs version mentioned in paper's subsection 4.2 like the following?
![image](https://user-images.githubusercontent.com/14728901/37717819-4d6372e6-2d5c-11e8-9895-2f90aeabf02b.png)
![image](https://user-images.githubusercontent.com/14728901/37717821-4ec045ec-2d5c-11e8-8d9d-a62369330e95.png)

**Comment by wuhuikai** [comment]
It's DGF not DGF<sub>s</sub>, the differences are:

| | DGF<sub>s</sub> | DGF<sub>b</sub> | DGF |
| --- | --- | --- | --- |
| Guidance Map | N | N | Y |
| Joint Training | N | Y | Y |

Figure 2 only shows guided filter layer used in image processing tasks. In supplementary material, Algorithm 2 and Algorithm 3 show the detail of guided filter layer used in image processing and computer vision separately, 

* Image Processing
    ```python
    hr_y = FastGuidedFilter(r, eps)(lr_x, lr_y, hr_x)
    ```
* Computer Vision
    ```python
    hr_y = GuidedFilter(r, eps)(hr_x, init_hr_y)
    ```

**Comment by hedes1992** [comment]
Thank you @wuhuikai, I get it in Algorithm 3 in paper.

**Comment by wuhuikai** [comment]
Yes, Algorithm 3 describes deep guided filter for computer vision tasks.

**Comment by pranav-gupta-7** [comment]
@wuhuikai Hi, I have a quick question. Why do we use “FastGuidedFilter” for image processing tasks and “GuidedFilter” for computer vision tasks? Also, can’t we use “ConvGuidedFilter” for both image processing and computer vision tasks? I’m a bit confused about these aspects.
