### ISSUE TITLE
OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0) 	 [[node shuffle_batch (defined at D:\DeepGuidedFilter_master\ComputerVision\MonoDepth\monodepth_dataloader.py:71) ]]

### ISSUE THREAD

**Issue by nanjingzhouyu** [wuhuikai/DeepGuidedFilter#20]
When I tried to train monodepth.main, It shows:
OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)
	 [[node shuffle_batch (defined at D:\DeepGuidedFilter_master\ComputerVision\MonoDepth\monodepth_dataloader.py:71) ]]
I have no idea if it's only happening on windows environment, could you help me with that?

**Comment by wuhuikai** [comment]
Make sure the dataset is placed correctly.
