### ISSUE TITLE
I cant generate Ground Truth img in Image Processing

### ISSUE THREAD

**Issue by nanjingzhouyu** [wuhuikai/DeepGuidedFilter#21]
When I use "matlab -r "prepare_dataset(   '512'); exit" -nodisplay" command on Matlab, It only generate an empty folder named "512", but without any TIF image inside it . 
The Matlab only gives a warning "Warning: Unrecognized command line option: nodisplay."
Could you please help me?

**Comment by nanjingzhouyu** [comment]
oh Its my fault, done with that, sorry

**Comment by nanjingzhouyu** [comment]
I got this error when  I run the Matlab code on my windows environment 

"Error using L0Smoothing (line 43)
Undefined function 'psf2otf' for input arguments of type 'double'.
Error in prepare_dataset (line 11)
    parfor idx = 1:length(imgs)"

could you please help me?

**Comment by wuhuikai** [comment]
It might be caused by wrong version of MatLab.

**Comment by nanjingzhouyu** [comment]
I got it, its because my Matlab doesn't have image processing toolbox! Thank you!
