### ISSUE TITLE
an application about guided filter to disentangle convolution effect from GAN image

### ISSUE THREAD

**Issue by BossunWang** [wuhuikai/DeepGuidedFilter#22]
Hi,
I have a preliminary idea about the application of guided filter.
GAN is more popular way to generate image for pre-process step on some area for example object recognition , style transfer.
but generator is a decoder which through many convolution layers, so that image become "convolution effect".
what I think about is FastGuidedFilter or GuidedFilter (not ConvGuidedFilter) can help to disentangle .
For example I would like to generated image more "real world image", I use FastGuidedFilter and generated image as input and real world image as guided image, then want to output a real picture.
Does this theory work?

**Comment by wuhuikai** [comment]
If input and guided image have similar edges and textures,  FastGuidedFilter should work.
