### ISSUE TITLE
I got "error: unrecognized arguments:" when I run test_time.py on Image processing. Could you pls help me?

### ISSUE THREAD

**Issue by nanjingzhouyu** [wuhuikai/DeepGuidedFilter#24]
=================================== ERRORS ====================================
________________________ ERROR collecting test_time.py ________________________
test_time.py:16: in <module>
    args = parser.parse_args()
C:\Users\86187\anaconda3\lib\argparse.py:1758: in parse_args
    self.error(msg % ' '.join(argv))
C:\Users\86187\anaconda3\lib\argparse.py:2508: in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
C:\Users\86187\anaconda3\lib\argparse.py:2495: in exit
    _sys.exit(status)
E   SystemExit: 2
------------------------------- Captured stderr -------------------------------
usage: _jb_pytest_runner.py [-h] [--gpu GPU] [--low_size LOW_SIZE]
                            [--full_size FULL_SIZE] [--iter_size ITER_SIZE]
                            [--model_id MODEL_ID]
_jb_pytest_runner.py: error: unrecognized arguments: D:/DeepGuidedFilter_master/ImageProcessing/DeepGuidedFilteringNetwork/test_time.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 1.22s ===============================

Process finished with exit code 2

**Comment by wuhuikai** [comment]
Your running script is wrong.

**Comment by nanjingzhouyu** [comment]
Could you be more specific? I'm new to python.

**Comment by wuhuikai** [comment]
Then learn `argparse`.

**Comment by nanjingzhouyu** [comment]
Sorry for the dumb question, I already know whats going on.
