### ISSUE TITLE
most examples use classical guided filter rather than the one in paper 

### ISSUE THREAD

**Issue by suruoxi** [wuhuikai/DeepGuidedFilter#25]
I'm wondering why  in most examples ,  you prefer the classical guided filter rather than the proposed   learnable filter layer in the paper.

**Comment by wuhuikai** [comment]
Do you mean `ConvGuidedFilter`? `ConvGuidedFilter` is an extension of our conference paper, we only have experiments on 5 image processing tasks. In computer vision tasks, we employ `GuidedFilterLayer` proposed in our conference paper.

**Comment by pranav-gupta-7** [comment]
@wuhuikai if you have proposed "ConvGuidedFilter" then you should also show all results (at least in supp.) to prove its efficiency. How did paper reviewers let this slide??? you proposed LearnableGuidedFilter and convguidedfilter but showing results with traditional guided filter 😂😂
