### ISSUE TITLE
can't reproduce results of Saliency_DSS with dgf

### ISSUE THREAD

**Issue by fereenwong** [wuhuikai/DeepGuidedFilter#27]
Thanks for sharing! I download the code and run it as readme. Without any modification, I can not reproduce the results of Saliency_DSS with dgf. Maybe the hyperparameters of training need to finetune?
With the provided pretrained checkpoint, I can get satisfactory results (I didn't measure the results yet.)

**Comment by wuhuikai** [comment]
Could you please be more specific about the training script you ran?

**Comment by fereenwong** [comment]
Aha, I suddenly noticed that the batch size is set as 1 in default..... Thanks for your reply, the new experiment result is still waiting for results.

--------------原始邮件--------------
发件人："Wu Huikai "<notifications@github.com&gt;;
发送时间：2020年9月14日(星期一) 晚上9:29
收件人："wuhuikai/DeepGuidedFilter" <DeepGuidedFilter@noreply.github.com&gt;;
抄送："fereenwong "<fereenwong@gmail.com&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [wuhuikai/DeepGuidedFilter] can't reproduce results of Saliency_DSS with dgf (#27)
-----------------------------------

 

 
Could you please be more specific about the training script you ran?
