### ISSUE TITLE
where can I get the supplementary material that describe the forward algorithm?

### ISSUE THREAD

**Issue by sunnylulu** [wuhuikai/DeepGuidedFilter#29]
Hi

Thanks for the great paper, I am still confused to understand the description in the Algorithm 1, could you tell me where can I find the supplementary material(The equations for propagating the gradients through guided filtering layer are shown in Algorithm 1, while the corresponding forward algorithm is presented in the **supplementary material**)?

Thanks in advance!

**Comment by wuhuikai** [comment]
Check ArXiv : )
