### ISSUE TITLE
the problem:RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by fengyicoder** [wuhuikai/DeepGuidedFilter#3]
hello, I try to run the command "python train_dgf.py --dgf --snapshots snapshots_dgf", however, the error appears as follows:
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Then, I try to change the iterSize and The error still exists. The memory of GPU is 3G. Is there any solution?

**Comment by wuhuikai** [comment]
If you're training the network for segmentation, a GPU with 12G memory is needed.

**Comment by fengyicoder** [comment]
Thanks!
