### ISSUE TITLE
Contributing a Multi-channel Guided Filter

### ISSUE THREAD

**Issue by adgaudio** [wuhuikai/DeepGuidedFilter#30]
Hello,

At request of @mangdian  in issue #14 , I am sharing code for my implementation of a Guided Filter for PyTorch that supports a multi-channel guide image and 1 channel source image.  The code is linked to in url below.  Can you please advise whether I should make my own repo for this, or whether we can add it here?  I thought it might be more helpful to the community to put implementations for the guided filter in one place.

https://gist.github.com/adgaudio/21f6aa699113c766c2c9ddd4c6144425

 Also, if anyone wishes to collaborate with me on academic papers, I would be happy to meet you over a web call or email with you.

Cheers,
Alex

**Comment by wuhuikai** [comment]
A PR is welcome ：）   Thanks for your contribution.
