### ISSUE TITLE
The question about setting FINE_SIZE in Config

### ISSUE THREAD

**Issue by Jebearssica** [wuhuikai/DeepGuidedFilter#32]
Since the default value is -1 and there's no change in whole repo. The following data fragment shows the "RandomCrop" will never employed. May I ask about the reason for settting FINE_SIZE as the parameter?

```python
RandomCrop(fine_size) if fine_size > 0 else None,
```

**Comment by wuhuikai** [comment]
One usage of `FINE_SIZE` is stacking multiple images with different size into a batch; however, we use `batch_size=1` in our experiment.
