### ISSUE TITLE
关于输入是RGB图像三通道，输出是alpha单通道信息

### ISSUE THREAD

**Issue by zhanghongyong123456** [wuhuikai/DeepGuidedFilter#36]
依照这个方式，
![image](https://user-images.githubusercontent.com/48466610/173029361-248363aa-65b7-471b-8c16-1d301e0b383e.png)
我使用了咱们项目的GuidedFilter_PyTorch，我有一个困惑，我输入的是一张RGB图像（三通道），我想得到对应的alpha（单通道），我该如何处理的，我发现计算的过程中，维度是不匹配的，难以计算，我该如何对RGB处理，我尝试使用RGB的均值mean，我发现会丢失信息，我想基于https://github.com/PeterL1n/RobustVideoMatting/blob/master/model/deep_guided_filter.py  实现，只由RGB输出对应的alpha，而不包含其他

**Comment by wuhuikai** [comment]
Maybe you can output 3 alphas, and then sum them up. Or, you can use a simple ConvNet to transform RGB into a single channel.

**Comment by zhanghongyong123456** [comment]
> Maybe you can output 3 alphas, and then sum them up. Or, you can use a simple ConvNet to transform RGB into a single channel.

ok ,非常感谢您的回复
