### ISSUE TITLE
Computer crash with convert_dng_to_tiff.py script

### ISSUE THREAD

**Issue by shreyasrajesh** [wuhuikai/DeepGuidedFilter#5]
I am having this issue with the convert_dng_to_tif.py script where my computer crashes immediately after running the script and the only option I am left with is a hard restart. I have even left it for a long time after running the script but that doesn't seem to solve the problem. The only change I have made to the script is in the path of the input file. Any help will be appreciated. Thanks.

**Comment by wuhuikai** [comment]
Sorry for the late reply.
1. Try to reduce # processes, ```N_PROCESS```
2. Ask for help in ```rawpy```

**Comment by shreyasrajesh** [comment]
Thank you. Fixed it by removing the threading procedure altogether. Reducing the number of process didnt seem to help.
