### ISSUE TITLE
what caused r_fast.png in GuidedFilter_TF/test and GuidedFilter_PyTorch/test lookes so different?

### ISSUE THREAD

**Issue by durgob** [wuhuikai/DeepGuidedFilter#8]
Hello @wuhuikai 

I have read the code in pytorch and tensorflow, they look quite similar to me. However, they produce different results, and I can't figure it out, it would be great if you could give me a clue.

Thanks!

**Comment by wuhuikai** [comment]
Have you tried to reproduce the two images yourself? I think the image in Github might not be consistent with the code.

**Comment by durgob** [comment]
Yep, I did. I have run the 'test_fast_guided_filter.py', but I can't get consistent result still. Here is the result of tensorflow
![r_fast_tf](https://user-images.githubusercontent.com/45822520/50414733-21dd4300-0852-11e9-84f9-0a40952db35b.jpg)
and this is result of pytorch
![r_fast](https://user-images.githubusercontent.com/45822520/50414747-39b4c700-0852-11e9-8d63-6894523ea134.jpg)

**Comment by wuhuikai** [comment]
I found the issue. The guided image in [pytorch](https://github.com/wuhuikai/DeepGuidedFilter/blob/abdebb9c7cc39bb21fb592a05484b923b001be25/GuidedFilteringLayer/GuidedFIlter_PyTorch/test/test_fast_guided_filter.py#L25) is the input image while it's the output image in [TF](https://github.com/wuhuikai/DeepGuidedFilter/blob/abdebb9c7cc39bb21fb592a05484b923b001be25/GuidedFilteringLayer/GuidedFilter_TF/test/test_fast_guided_filter.py#L22).

**Comment by durgob** [comment]
OK, they look the same now, thank you!

**Comment by dvolgyes** [comment]
I also ran into this issue, but i fail to see why the fast guided filter outputs look similar, 
while the guided filter outputs look different. Could you elaborate your last comment?
Or if there is a code change, could you commit it? Thanks.

**Comment by wuhuikai** [comment]
The bug is in the test scripts:
In `TF`, the inputs are `[lr_rgb, lr_gt, gt]]`;
In `PT`, the inputs are `[lr_rgb, lr_gt, rgb]]`.
So, the test results are different.

**Comment by dvolgyes** [comment]
I see, thanks for the explanation. Do you mind merging the fix? 
I guess many people run into this issue.
 
Also, for the pytorch guided filter i get strange output.
Maybe it is different pytorch version, etc., but i tried to fix the warnings (upsample vs interpolate, etc.),
but i could not find the reason. So the r.jpg looks like this:
![r](https://user-images.githubusercontent.com/425560/62832011-9077e100-bc28-11e9-9fa0-18c9b692f289.jpg)
Any advice for this issue?

**Comment by wuhuikai** [comment]
1. `PR` is welcome.
2. It's the correct output image. To obtain a high-quality image, please tune the hyper-params in `GuidedFilter`, i.e. `radius` and `eps`.
