### ISSUE TITLE
System gets hanged and f measure difference

### ISSUE THREAD

**Issue by tuhinkm** [wuhuikai/DeepGuidedFilter#9]
Hi, 
I am having the following issues/doubts:
1. My system gets hanged when i try to run the saliency part of the code, for both test.py and predict.py. I use the pretrained model shared. Can you please help.
2. The paper states the  F measure to be around 91% on DSS. However, the DSS method itself has reported a 92% F measure. Can you please explain the reason for the difference.

**Comment by wuhuikai** [comment]
1. Please give me more information about your problem.
2. We couldn't reproduce the reported F measure (92% ) with Pytorch :(

**Comment by tuhinkm** [comment]
Thanks for the promt reply.
1. I get the one line print of the parser_args outputs. Then the system hangs for testing. Not sure why.
2. Can you please share your saliency (saliency maps) results reported in google drive, with and without Deep Guided Filter. Will be of great help for comparison.

**Comment by wuhuikai** [comment]
1. Without much info, I couldn't reproduce your problem. I suggest using PyCharm for debugging.
2. Currently, I'm busy with ICCV. I can release the results after then.

**Comment by tuhinkm** [comment]
Sure.
With the SalMetric implement I am getting the following error. Can you help me out 
1. With C++: make

[ 50%] Building CXX object src/CMakeFiles/salmetric.dir/sal_metric.cpp.o
In file included from /home/user/Documents/DSS_basic_results/SalMetric/src/sal_metric.cpp:7:0:
/home/user/Documents/DSS_basic_results/SalMetric/include/sal_metric.hpp:51:24: error: ‘constexpr’ needed for in-class initialization of static data member ‘const float SalMetric::EPSILON’ of non-integral type [-fpermissive]
     static const float EPSILON = 1e-4;
                        ^~~~~~~
/home/user/Documents/DSS_basic_results/SalMetric/include/sal_metric.hpp:52:24: error: ‘constexpr’ needed for in-class initialization of static data member ‘const float SalMetric::BETA’ of non-integral type [-fpermissive]
     static const float BETA = 0.3;
                        ^~~~
src/CMakeFiles/salmetric.dir/build.make:62: recipe for target 'src/CMakeFiles/salmetric.dir/sal_metric.cpp.o' failed
make[2]: *** [src/CMakeFiles/salmetric.dir/sal_metric.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/salmetric.dir/all' failed
make[1]: *** [src/CMakeFiles/salmetric.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

2. With python: 
running install
running build
running build_ext
building 'build.salmetric' extension
gcc -pthread -B /home/user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./include -I/usr/local/include/ -I/usr/local/include/opencv2/ -I/home/user/anaconda3/include/python3.6m -c ./python/salmetric.cpp -o build/temp.linux-x86_64-3.6/./python/salmetric.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from ./python/salmetric.cpp:313:0:
./include/sal_metric.hpp:51:24: error: ‘constexpr’ needed for in-class initialization of static data member ‘const float SalMetric::EPSILON’ of non-integral type [-fpermissive]
     static const float EPSILON = 1e-4;
                        ^~~~~~~
./include/sal_metric.hpp:52:24: error: ‘constexpr’ needed for in-class initialization of static data member ‘const float SalMetric::BETA’ of non-integral type [-fpermissive]
     static const float BETA = 0.3;
                        ^~~~
error: command 'gcc' failed with exit status 1

**Comment by wuhuikai** [comment]
The saliency maps are in [here](https://drive.google.com/open?id=1FPj7Lc-Ch7N-1n5R--wbmQXvNpl1YbyI), where `dss_dgf.zip` is with DGF and `dss.zip` is without DGF.
`{id}.png` is the ground truth, `{id}_sal.png` is the saliency map and `{id}_sal_{thres}.png` is the result after applying a threshold.
`test.txt` is the list of test images and `test_result.txt` is the performance.
